# -*- coding: utf-8 -*-
"""Copy of IRIS Flower classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cqGT5llp_XBKPUKHsdbYcTjFQpqDbCko

**Exploratory Data Analysis on IRIS Dataset**
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

iris_flower=pd.read_csv("/IRIS.csv")

print(iris_flower)

print(iris_flower.shape)

print(iris_flower.columns)

"""*Total No of Species in the given dataset*"""

iris_flower["species"].value_counts()

"""**Scatter Plot**"""

iris_flower.plot(kind="scatter", x="petal_length", y="petal_width")
plt.show()

iris_flower.plot(kind="scatter", x="sepal_length", y="sepal_width")
plt.show()

"""**Convert data into Pandas daframe**"""

df=pd.DataFrame(iris_flower, columns=["sepal_length", "sepal_width","petal_length, petal_width"])

df.tail()

df.head()

df['target']=iris_flower['species'].map

df.describe()

print(df.groupby('target').size())

df.plot(kind='box', subplots=True, layout=(2,2), sharex=False, sharey=False)
plt.show()

df.hist(figsize=(12,12))
plt.show()

sns.pairplot(df, hue="target")

sns.catplot(x="sepal_length", y="sepal_width",palette='husl', hue="target", kind="swarm", data=df)